version: "3"

services:
  microService:
    image: hgq_docker:1.6  #镜像名称
    container_name: ms01   #容器名称
    ports: #映射端口
      - "6001:6001"
    volumes: #容器卷
      - /hgq/microService:/data
    networks: #网络
      - hgq_net
    depends_on: #启动服务顺序
      - redis
      - mysql

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /hgq/redis/redis.conf:/etc/redis/redis.conf
      - /hgq/redis/data:/data
    networks:
      - hgq_net
    command: redis-server /etc/redis/redis.conf

  mysql:
   image: mysql:5.7
   environment: # 设置mysql相关信息
     MYSQL_ROOT_PASSWORD: '123456'
     MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
     MYSQL_DATABASE: 'demo'
     MYSQL_USER: 'hgq'
     MYSQL_PASSWORD: '123456'
   ports:
     - "3306:3306"
   volumes:
     - /hgq/mysql/log:/var/log/mysql
     - /hgq/mysql/data:/var/lib/mysql
     - /hgq/mysql/conf:/etc/mysql/conf.d
   networks:
     - hgq_net
   command: --default-authentication-plugin=mysql_native_password #解决外部无法访问

# 创建网络
networks:
  hgq_net: