server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379

swagger:
  # 是否开启swagger
  enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

ncamc:
  jwt:
    secret: ncamc@Login(Auth}*^31)&ncamcjava% # 登录校验的密钥
    pubKeyPath: E:\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: E:\\tmp\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: NCAMC_TOKEN
    cookieMaxAge: 30 #cookie在浏览器上的最大存活时间 单位为分钟

scheduleinfo:
  scheduletask: 0/30 * * * * ?